"""empty message

Revision ID: a6dbbc514fdd
Revises: 28e4bbff2cf1
Create Date: 2019-03-17 09:17:54.909628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6dbbc514fdd'
down_revision = '28e4bbff2cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='Transaction_Details')
    op.drop_table('Transaction_Details')
    op.add_column('Transactions', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('Transactions', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('Transactions', sa.Column('qty', sa.Integer(), nullable=True))
    op.drop_column('Transactions', 'shipping_method_id')
    op.drop_column('Transactions', 'payment_method_id')
    op.drop_column('Transactions', 'total_qty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('total_qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('Transactions', sa.Column('payment_method_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('Transactions', sa.Column('shipping_method_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('Transactions', 'qty')
    op.drop_column('Transactions', 'product_id')
    op.drop_column('Transactions', 'price')
    op.create_table('Transaction_Details',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('transaction_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'Transaction_Details', ['id'], unique=True)
    # ### end Alembic commands ###
